rTorrent: Add stability patches
crazy-max/docker-rtorrent-rutorrent pull request #286
Opened 2023-12-05 16:47 UTC by stickz

This commit adds multiple stability patches to rtorrent. I have tested these for multiple months. The reason for modifying the software is to resolve stability issues. The software owner is no longer releasing new versions.

**Note:** I do not have a configuration to build this docker image. Modification may be required to install these patches.

**libtorrent**
- Fixes an issue where the throttle plugin on ruTorrent is required to limit upload/download speed to 1gbps.

**rTorrent**
- Fixes a crash caused by some hardening flags during the build process.
- Fixes a crash caused by ruTorrent sending invalid xmlrpc data to rTorrent.
- Fixes a crash caused by external configurations sending invalid xmlrpc data to rTorrent.
- Fixes an issue where torrent information will not update if too many torrents are running.
- Fixes an issue where a power loss during torrent session saving will corrupt torrents.

2023-12-05 17:02 UTC, stickz commented
@crazy-max I can see from the build log these patches installed successfully and the build passed. I do not have a configuration to build this docker image. The only step required to build the docker image and ensure rTorrent runs properly before pushing changes. I have tested these changes for months. There should be zero issues and significantly improved rTorrent stability.

2023-12-12 14:06 UTC, crazy-max requested changes
Overall LGTM thanks

I saw your upstream changes https://github.com/rakshasa/rtorrent/pulls/stickz, hopefully it will be considered in the future. The rotrrent/libtorrent still look active but yeah without tags we can't expect proper stability.

2023-12-14 21:27 UTC, stickz commented
> Overall LGTM thanks
> 

All fixed up. Suggestions implemented.

2023-12-14 21:31 UTC, crazy-max approved these changes
LGTM thanks again!

2023-12-14 21:31 UTC, merged

2023-12-14 21:34 UTC, crazy-max commented
Small nit as follow-up would be to update this section in the README: https://github.com/crazy-max/docker-rtorrent-rutorrent#features about `Latest rTorrent / libTorrent release compiled from source` to say some patches are also applied to enhance rTorrent stability or smth like that.

2023-12-14 21:49 UTC, stickz commented
> Small nit as follow-up would be to update this section in the README: https://github.com/crazy-max/docker-rtorrent-rutorrent#features about `Latest rTorrent / libTorrent release compiled from source` to say some patches are also applied to enhance rTorrent stability or smth like that.

I will update that next pull request when 10gbps throttle support is added. This container will be the first to support 10gbps by default on ruTorrent with throttling capabilities. This will bring the configuration into the next decade!