Bump ruTorrent to v5.0 stable
crazy-max/docker-rtorrent-rutorrent pull request #400
Opened 2024-10-10 12:49 UTC by ghisch

https://github.com/Novik/ruTorrent/commit/664a83f228d5184d7130cb854e08598fac4b1ce5

https://github.com/Novik/ruTorrent/releases/tag/v5.0.0

2024-10-10 14:06 UTC, stickz requested changes

2024-10-10 14:06 UTC, stickz commented on Dockerfile
>  # v4.3.6
Adjust comment here.

2024-10-10 14:14 UTC, ghisch commented on Dockerfile
>  # v4.3.6
Done, sorry I missed it.

2024-10-10 14:28 UTC, stickz approved these changes

2024-10-14 23:42 UTC, stickz commented
@crazy-max PR #397 is good to go. 

I would recommend closing this PR in favour of `ruTorrent v5.1` releasing in 2 weeks. Here is our roadmap for development https://github.com/Novik/ruTorrent/discussions/2740 We are dropping support for `ruTorrent v5.0`. We choose to include all our hotfixes in one big minor release, with a couple critical feature improvements to accelerate development.

2024-10-15 10:41 UTC, closed without merging